package com.videotagger.service;

import com.videotagger.entity.*;
import com.videotagger.mapper.*;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class VideoSourceRemapService {
    public record Preview(long clipId,long oldStartMs,Long oldEndMs,long newStartMs,Long newEndMs,double confidence,boolean blocked,String reason){}
    private final VideoTimeMappingMapper mappingMapper; private final VideoTimeMappingAnchorMapper anchorMapper; private final ClipMapper clipMapper;
    public VideoSourceRemapService(VideoTimeMappingMapper mappingMapper,VideoTimeMappingAnchorMapper anchorMapper,ClipMapper clipMapper){this.mappingMapper=mappingMapper;this.anchorMapper=anchorMapper;this.clipMapper=clipMapper;}
    public VideoTimeMapping create(long oldAssetId,long newAssetId,List<VideoTimeMappingAnchor> anchors){long now=System.currentTimeMillis();VideoTimeMapping mapping=new VideoTimeMapping();mapping.setOldAssetId(oldAssetId);mapping.setNewAssetId(newAssetId);mapping.setStatus("UNMAPPED");mapping.setCreatedAt(now);mapping.setUpdatedAt(now);mappingMapper.insert(mapping);int order=0;for(VideoTimeMappingAnchor anchor:anchors==null?List.<VideoTimeMappingAnchor>of():anchors){anchor.setTimeMappingId(mapping.getId());if(anchor.getSortOrder()==null)anchor.setSortOrder(order++);anchor.setCreatedAt(now);anchorMapper.insert(anchor);}recalculate(mapping.getId());return mappingMapper.selectById(mapping.getId());}
    public VideoTimeMapping recalculate(long mappingId){VideoTimeMapping mapping=mappingMapper.selectById(mappingId);if(mapping==null)throw new IllegalArgumentException("Mapping not found");List<VideoTimeMappingAnchor> anchors=anchorMapper.selectList(new com.baomidou.mybatisplus.core.conditions.query.QueryWrapper<VideoTimeMappingAnchor>().eq("time_mapping_id",mappingId).orderByAsc("sort_order"));var result=VideoTimeMappingCalculator.calculate(anchors,120);mapping.setStatus(result.state());mapping.setOffsetMs(result.offsetMs());mapping.setDriftRatio(result.driftRatio());mapping.setConfidence(result.confidence());mapping.setNotes(result.reason());mapping.setUpdatedAt(System.currentTimeMillis());mappingMapper.updateById(mapping);return mapping;}
    public List<Preview> preview(long mappingId){VideoTimeMapping mapping=recalculate(mappingId);List<Clip> clips=clipMapper.listByVideoAsset(mapping.getOldAssetId());List<Preview> result=new ArrayList<>();for(Clip clip:clips){long oldStart=clip.getStartMs()!=null?clip.getStartMs():Math.round(clip.getTimestampSec()*1000);Long oldEnd=clip.getEndMs()!=null?clip.getEndMs():clip.getEndSec()==null?null:Math.round(clip.getEndSec()*1000);boolean blocked="INCOMPATIBLE".equals(mapping.getStatus());long newStart=apply(mapping,oldStart);Long newEnd=oldEnd==null?null:apply(mapping,oldEnd);double confidence=mapping.getConfidence()==null?0:mapping.getConfidence();result.add(new Preview(clip.getId(),oldStart,oldEnd,newStart,newEnd,confidence,blocked,blocked?"INCOMPATIBLE_MAPPING":confidence<0.7?"LOW_CONFIDENCE":"READY"));}return result;}
    public List<Clip> confirm(long mappingId,List<Long> clipIds){VideoTimeMapping mapping=recalculate(mappingId);if("INCOMPATIBLE".equals(mapping.getStatus()))throw new IllegalStateException("Mapping is incompatible");List<Clip> created=new ArrayList<>();for(Preview preview:preview(mappingId)){if(clipIds!=null&&!clipIds.contains(preview.clipId()))continue;Clip old=clipMapper.selectById(preview.clipId());Clip copy=new Clip();copy.setTitle(old.getTitle());copy.setUrl(old.getUrl());copy.setVideoFp(old.getVideoFp());copy.setEpisodeId(old.getEpisodeId());copy.setVideoAssetId(mapping.getNewAssetId());copy.setSourceRevision(old.getSourceRevision());copy.setTimeMappingId(mappingId);copy.setStartMs(preview.newStartMs());copy.setEndMs(preview.newEndMs());copy.setTimestampSec(preview.newStartMs()/1000d);copy.setEndSec(preview.newEndMs()==null?null:preview.newEndMs()/1000d);copy.setVideoDuration(old.getVideoDuration());copy.setTag(old.getTag());copy.setNote(old.getNote());copy.setCoverPath(old.getCoverPath());copy.setDetailCoverPath(old.getDetailCoverPath());copy.setMaterialState("REFERENCE_ONLY");copy.setCreatedAt(System.currentTimeMillis());clipMapper.insert(copy);created.add(copy);}mapping.setStatus("CONFIRMED");mapping.setConfirmedAt(System.currentTimeMillis());mapping.setUpdatedAt(System.currentTimeMillis());mappingMapper.updateById(mapping);return created;}
    private long apply(VideoTimeMapping m,long value){double drift=m.getDriftRatio()==null?0:m.getDriftRatio();long offset=m.getOffsetMs()==null?0:m.getOffsetMs();return Math.round(value*(1d+drift)+offset);}
}